// <auto-generated />
using aureliadotnetcore.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace aureliadotnetcore.Migrations
{
    [DbContext(typeof(MoviesData))]
    [Migration("20180105220727_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("aureliadotnetcore.Model.AthleteItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("age");

                    b.Property<string>("athlete");

                    b.Property<int>("bronze");

                    b.Property<string>("country");

                    b.Property<string>("date");

                    b.Property<int>("gold");

                    b.Property<int>("silver");

                    b.Property<string>("sport");

                    b.Property<int>("total");

                    b.Property<int>("year");

                    b.HasKey("id");

                    b.ToTable("Athlete");
                });

            modelBuilder.Entity("aureliadotnetcore.Model.MovieItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ReleaseYear");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
